2018-07-31 17:33:06,220 - Utils.log_utils - WARNING - Traceback (most recent call last):
  File "F:/scribe2/Client/Auto_Update.py", line 32, in test_ok
    timeout=10)
  File "F:\scribe2\Client\venv\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "F:\scribe2\Client\venv\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\scribe2\Client\venv\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\scribe2\Client\venv\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "F:\scribe2\Client\venv\lib\site-packages\requests\adapters.py", line 410, in send
    conn = self.get_connection(request.url, proxies)
  File "F:\scribe2\Client\venv\lib\site-packages\requests\adapters.py", line 308, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "F:\scribe2\Client\venv\lib\site-packages\requests\adapters.py", line 188, in proxy_manager_for
    **proxy_kwargs
  File "F:\scribe2\Client\venv\lib\site-packages\requests\adapters.py", line 45, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

2018-08-09 11:56:15,493 - Utils.log_utils - WARNING - Traceback (most recent call last):
  File "F:/scribe2/Client/Auto_Update.py", line 64, in test_ok
    with open(self.proxy_filt_path,'r+') as frw:
OSError: [Errno 22] Invalid argument: 'D:/Privoxy/config.txt\n'

